# DAV 5400 Spring 2019 Week 4 Assignment

## 1.Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.

In [126]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [4]:
print("Common:",np.union1d(a,b)) #Compute the sorted union of elements

Common: [ 1  2  3  4  5  6  7  8  9 10]


## 2. Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

In [26]:
arr = np.arange(1,16).reshape(3,5) #range from 1 to 15 and then reshape

In [27]:
arr.T #transpose

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## 3. You are given the following two arrays:
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [31]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

In [39]:
print(np.setdiff1d(a,b)) #Set difference, elements in a that are not in b

[ 1  7  8 15]


## Task 4

Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a NumPy array wherein you can record the **cumulative miles** you recorded each day during your trip. Then use your Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal fatigue/soreness. For the **remaining 31 days**, you would have covered the entire distance between NYC and Key West. Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your approach to this problem, including the ways in which you decided to make use of NumPy.

According to Google Map, the total miles would be 1548, so the rest distance would be **1428 miles**. Therefore, the minimal average miles I have to ride everyday is **47** in remaining 31 days.

In [122]:
import random
ride = []
mile = 0

for x in np.random.randint(30,60,30): #Base on the assumption, I would ride 30 to 60 miles perday and count for 31 days
    mile = mile + x
    ride.append(mile)   
    if len(ride) == 31: #Pause the loop in 31 days
        break
ride = ride + random.sample(ride,4) #randomly take 4 sample and then copy to the list to present the resting days
ride.append(1428) #add the last day to the list
ride.sort()
print(ride)
len(ride)

[37, 67, 105, 144, 144, 193, 249, 249, 288, 328, 378, 421, 462, 493, 538, 587, 634, 673, 711, 769, 819, 860, 900, 937, 983, 1030, 1030, 1078, 1078, 1131, 1165, 1210, 1247, 1299, 1428]


35

## Task 5

###5. Open the Jupyter Notebook provided to you with this assignment. The first code block within that file will load a small data set from a GitHub repository into a NumPy 2D array. The original source of that data contains an overview of its contents:

https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m

Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using NumPy’s slicing, methods, and functions:

1. What is the maximum yearly NYC consumption of water in millions of gallons per day?
2. How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
3. What is the mean and the standard deviation of the per capita daily water consumption?
4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

Please note that it may take a bit of time for Jupyter to load the data set from the GitHub repository. You will know that process has finished once the results of the ‘type(nyc_water)’ command get displayed within your copy of the notebook.

In [165]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('/Users/johnnyzhu/Downloads/Water_Consumption_In_The_New_York_City-2.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [144]:
#1 What is the maximum yearly NYC consumption of water in millions of gallons per day?
np.max(nyc_water,axis=0)[2]

1512.0

In [147]:
#2 How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
np.shape(nyc_water)[0]

39

In [151]:
#3 What is the mean and the standard deviation of the per capita daily water consumption?
print(np.mean(nyc_water,axis=0)[3])
print(np.std(nyc_water,axis=0)[3])

160.30769230769232
31.518943303706244


In [161]:
#4 What is the increase or decrease in population from year to year?
sorted_nyc_water = nyc_water.sort()
np.diff(nyc_water,axis=1)[:,1]

array([ 467. ,  474. ,  672. ,  600. ,  559. ,  519. ,  659. ,  635. ,
        540. ,  504. ,  587. ,  566. ,  522. ,  623. ,  937. ,  910. ,
        971. , 1014. ,  990. ,  791.5, 1002.9, 1001.5,  904.5,  817. ,
        867. , 1018. ,  759.6,  893. , 1006. , 1006.9,  778.5,  909.3,
        761.8,  698.1,  669.3, 1026.8,  624.5,  866.4,  636.3])